[workspace]
resolver = "3"
members = [
    "raqim-core",
    "raqim-cli"
, "raqim-mcp", "raqim-py", "raqim-siege"]

[patch.crates-io]
# This must be the full path to the repository
chrono = { git = "https://github.com/chronotope/chrono", tag = "v0.4.38" }

[profile.release]
opt-level = 3
debug = 0
strip = true

[profile.dev]
debug = 1

