[package]
name = "raqim-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
raqim-core = {path = "../raqim-core", default-features = false, features = ["mock-embedding"]}
rkyv = "0.8.15"
blake3 = "1.5"
tokio = { version = "1", features = ["full"] }


serde_json = "1.0.149"

reqwest = { version = "0.13.2", features = ["blocking", "json"] }

clap = { version = "4.5", features = ["derive", "env"] } # For CLI parsing
serde = { version = "1.0", features = ["derive"] }

hex =  "0.4"

ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
rand = "0.8"
