[package]
name = "raqim-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["native-embedding"]
native-embedding = ["dep:fastembed"]
mock-embedding = []

[dependencies]
fastembed = { version = "5.12", optional = true }
# The Zero-copy Data plane
rkyv = { version = "0.8.15", features = ["bytecheck"] }

# The State Engine (CRDTs)
loro = "1.0"

# The Nucleus Async Runtime
tokio = { version = "1.37", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "sync", "signal"] }

blake3 =  "1.5"

zenoh = "1.7.2"
sysinfo = "0.30"
hex =  "0.4"
uuid = { version = "1.10", features = ["v7", "serde"] }

lancedb = "0.9"
arrow-array = "52.2"
arrow-schema = "52.2"

anyhow = "1.0"

base64 = "0.23.0"
crc32fast = "1.4"

futures = "0.3"
clap = { version = "4.5", features = ["derive", "env"] } # For CLI parsing
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
memmap2 = "0.9" 
rand = "0.10.0"
rand_core = { version = "0.6", features = ["getrandom"] }
reqwest = { version = "0.13.2", features = ["blocking", "json", "stream" ] }
notify = "8.2.0"
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["rust_crypto", "use_pem"] }
serde_json = "1.0.149"
ed25519-dalek = {version = "2.2.0", default-features = false, features = ["rand_core", "serde"]}
parking_lot = "0.12"
dashmap = "6.1.0"

axum = { version = "0.7.9", features = ["ws", "macros", "multipart"] }
futures-util = "0.3"
tokio-stream = { version = "0.1.18", features = ["sync"] }
aho-corasick = "1.1.4"
async-trait = "0.1.89"
fs_extra = "1.3.0"
toml_edit = "0.25.11"
tokio-util = "0.7.18"
postcard = "1.1.3"
 
tower-http = { version = "0.5", features = ["cors", "catch-panic"] }

[build-dependencies]
cc = "1.0"